overwrite: true
schema: "http://localhost:3001/graphql"
documents: "src/**/*.gql"
generates:
  src/types/index.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
